name: "release"

on:
  repository_dispatch:
    types: [on-demand-release]

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: "--target aarch64-apple-darwin"
            name: macOS arm64
          - platform: macos-latest
            args: "--target x86_64-apple-darwin"
            name: macOS Intel
          - platform: "windows-latest"
            args: ""
            name: Windows
    
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out project
        uses: actions/checkout@v4
        with:
          repository: aovoq/temo
          token: ${{ secrets.GH_TOKEN_FOR_CHECKOUT }}
          ref: ${{ github.event.client_payload.sha }}
      
      - name: Test Echo
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.sha }}'"
          
          
